import { Course } from "./types";

export const mockCourses: Course[] = [
  {
    id: "organic-chem",
    name: "Organic Chemistry",
    credits: 4,
    targetGrade: 90,
    finalExamWeight: 30,
    categories: [
      { name: "Labs", weight: 25 },
      { name: "Quizzes", weight: 20 },
      { name: "Midterm", weight: 25 },
      { name: "Final Exam", weight: 30 },
    ],
    assignments: [
      {
        id: "org-lab-3",
        courseId: "organic-chem",
        name: "Lab Report 3",
        category: "Labs",
        dueDate: "2026-03-18",
        status: "completed",
        scoreEarned: 88,
        scorePossible: 100,
      },
      {
        id: "org-lab-4",
        courseId: "organic-chem",
        name: "Lab Report 4",
        category: "Labs",
        dueDate: "2026-03-27",
        status: "in-progress",
        scoreEarned: null,
        scorePossible: 100,
      },
      {
        id: "org-quiz-5",
        courseId: "organic-chem",
        name: "Mechanisms Quiz",
        category: "Quizzes",
        dueDate: "2026-03-16",
        status: "completed",
        scoreEarned: 15,
        scorePossible: 20,
      },
      {
        id: "org-midterm-1",
        courseId: "organic-chem",
        name: "Midterm I",
        category: "Midterm",
        dueDate: "2026-03-10",
        status: "completed",
        scoreEarned: 78,
        scorePossible: 100,
      },
      {
        id: "org-final",
        courseId: "organic-chem",
        name: "Comprehensive Final",
        category: "Final Exam",
        dueDate: "2026-05-12",
        status: "not-started",
        scoreEarned: null,
        scorePossible: 100,
      },
    ],
  },
  {
    id: "data-structures",
    name: "Data Structures",
    credits: 4,
    targetGrade: 92,
    finalExamWeight: 25,
    categories: [
      { name: "Projects", weight: 40 },
      { name: "Quizzes", weight: 20 },
      { name: "Midterm", weight: 15 },
      { name: "Final Exam", weight: 25 },
    ],
    assignments: [
      {
        id: "ds-proj-1",
        courseId: "data-structures",
        name: "Linked List Project",
        category: "Projects",
        dueDate: "2026-03-20",
        status: "completed",
        scoreEarned: 93,
        scorePossible: 100,
      },
      {
        id: "ds-proj-2",
        courseId: "data-structures",
        name: "Tree Visualizer",
        category: "Projects",
        dueDate: "2026-04-01",
        status: "in-progress",
        scoreEarned: null,
        scorePossible: 100,
      },
      {
        id: "ds-quiz-4",
        courseId: "data-structures",
        name: "Complexity Quiz",
        category: "Quizzes",
        dueDate: "2026-03-14",
        status: "completed",
        scoreEarned: 18,
        scorePossible: 20,
      },
      {
        id: "ds-midterm",
        courseId: "data-structures",
        name: "Midterm",
        category: "Midterm",
        dueDate: "2026-03-05",
        status: "completed",
        scoreEarned: 87,
        scorePossible: 100,
      },
      {
        id: "ds-final",
        courseId: "data-structures",
        name: "Final Exam",
        category: "Final Exam",
        dueDate: "2026-05-09",
        status: "not-started",
        scoreEarned: null,
        scorePossible: 100,
      },
    ],
  },
  {
    id: "statistics-ii",
    name: "Statistics II",
    credits: 3,
    targetGrade: 88,
    finalExamWeight: 35,
    categories: [
      { name: "Homework", weight: 25 },
      { name: "Labs", weight: 15 },
      { name: "Tests", weight: 25 },
      { name: "Final Exam", weight: 35 },
    ],
    assignments: [
      {
        id: "stats-hw-6",
        courseId: "statistics-ii",
        name: "Regression Homework",
        category: "Homework",
        dueDate: "2026-03-15",
        status: "completed",
        scoreEarned: 41,
        scorePossible: 50,
      },
      {
        id: "stats-hw-7",
        courseId: "statistics-ii",
        name: "Bayes Practice",
        category: "Homework",
        dueDate: "2026-03-28",
        status: "in-progress",
        scoreEarned: null,
        scorePossible: 50,
      },
      {
        id: "stats-lab-3",
        courseId: "statistics-ii",
        name: "R Lab 3",
        category: "Labs",
        dueDate: "2026-03-22",
        status: "completed",
        scoreEarned: 17,
        scorePossible: 20,
      },
      {
        id: "stats-test-1",
        courseId: "statistics-ii",
        name: "Unit Test 1",
        category: "Tests",
        dueDate: "2026-03-08",
        status: "completed",
        scoreEarned: 76,
        scorePossible: 100,
      },
      {
        id: "stats-final",
        courseId: "statistics-ii",
        name: "Final Exam",
        category: "Final Exam",
        dueDate: "2026-05-14",
        status: "not-started",
        scoreEarned: null,
        scorePossible: 100,
      },
    ],
  },
];
