import { Course } from "./types";

export const mockCourses: Course[] = [
  {
    id: "mis-213-009",
    name: "Business Tech & Intelligence",
    credits: 3,
    targetGrade: 95,
    finalExamWeight: 25,
    categories: [
      { name: "Coursework", weight: 75 },
      { name: "Final Exam", weight: 25 },
    ],
    assignments: [
      {
        id: "mis-current-grade",
        courseId: "mis-213-009",
        name: "Current grade snapshot",
        category: "Coursework",
        dueDate: "2026-03-24",
        status: "completed",
        scoreEarned: 100,
        scorePossible: 100,
      },
      {
        id: "mis-access-group-example",
        courseId: "mis-213-009",
        name: "Access Group Example",
        category: "Coursework",
        dueDate: "2026-03-19",
        status: "in-progress",
        scoreEarned: null,
        scorePossible: 100,
      },
      {
        id: "mis-part-2-access-tutorial",
        courseId: "mis-213-009",
        name: "Part 2 Access Tutorial",
        category: "Coursework",
        dueDate: "2026-03-24",
        status: "in-progress",
        scoreEarned: null,
        scorePossible: 3,
      },
      {
        id: "mis-final",
        courseId: "mis-213-009",
        name: "Final Exam",
        category: "Final Exam",
        dueDate: "2026-05-05",
        status: "not-started",
        scoreEarned: null,
        scorePossible: 100,
      },
    ],
  },

  {
    id: "evs-195-001",
    name: "Intro to Environmental Science",
    credits: 3,
    targetGrade: 94,
    finalExamWeight: 25,
    categories: [
      { name: "Assignments", weight: 75 },
      { name: "Exam 1", weight: 25 },
    ],
    assignments: [
      {
        id: "evs-quiz-1-2",
        courseId: "evs-195-001",
        name: "Quiz - Chapters 1 & 2",
        category: "Assignments",
        dueDate: "2026-02-05",
        status: "completed",
        scoreEarned: 8,
        scorePossible: 10,
      },
      {
        id: "evs-science-daily",
        courseId: "evs-195-001",
        name: "Assignment 1 - Science Daily",
        category: "Assignments",
        dueDate: "2026-02-12",
        status: "completed",
        scoreEarned: 10,
        scorePossible: 10,
      },
      {
        id: "evs-quiz-3-4",
        courseId: "evs-195-001",
        name: "Quiz Chapters 3 and 4",
        category: "Assignments",
        dueDate: "2026-02-17",
        status: "completed",
        scoreEarned: 9,
        scorePossible: 10,
      },
      {
        id: "evs-ch5-quiz",
        courseId: "evs-195-001",
        name: "Chapter 5 Quiz",
        category: "Assignments",
        dueDate: "2026-02-18",
        status: "completed",
        scoreEarned: 4,
        scorePossible: 5,
      },
      {
        id: "evs-exam-1",
        courseId: "evs-195-001",
        name: "Exam 1",
        category: "Exam 1",
        dueDate: "2026-02-19",
        status: "completed",
        scoreEarned: 92,
        scorePossible: 100,
      },
      {
        id: "evs-quiz-7-9",
        courseId: "evs-195-001",
        name: "Quiz - Chapters 7 & 9",
        category: "Assignments",
        dueDate: "2026-03-19",
        status: "completed",
        scoreEarned: 10,
        scorePossible: 10,
      },
      {
        id: "evs-marine-protected-areas",
        courseId: "evs-195-001",
        name: "Assignment 2 - Marine Protected Areas",
        category: "Assignments",
        dueDate: "2026-03-25",
        status: "in-progress",
        scoreEarned: null,
        scorePossible: 10,
      },
      {
        id: "evs-ch16-quiz",
        courseId: "evs-195-001",
        name: "Chapter 16 Quiz",
        category: "Assignments",
        dueDate: "2026-03-26",
        status: "not-started",
        scoreEarned: null,
        scorePossible: 5,
      },
    ],
  },

  {
    id: "ecn-222-002-003",
    name: "Principles of Economics",
    credits: 3,
    targetGrade: 98,
    finalExamWeight: 25,
    categories: [
      { name: "Homework Assignments", weight: 30 },
      { name: "Class Participation", weight: 5 },
      { name: "Activity Assignments", weight: 15 },
      { name: "Exam 1", weight: 12.5 },
      { name: "Exam 2", weight: 12.5 },
      { name: "Final Exam", weight: 25 },
    ],
    assignments: [
      {
        id: "ecn-attendance-1-12",
        courseId: "ecn-222-002-003",
        name: "Attendance 1/12",
        category: "Class Participation",
        dueDate: "2026-01-12",
        status: "completed",
        scoreEarned: 1,
        scorePossible: 1,
      },
      {
        id: "ecn-homework-ch1",
        courseId: "ecn-222-002-003",
        name: "Homework (Ch1)",
        category: "Homework Assignments",
        dueDate: "2026-01-19",
        status: "completed",
        scoreEarned: 100,
        scorePossible: 100,
      },
      {
        id: "ecn-activity-1",
        courseId: "ecn-222-002-003",
        name: "Activity 1: Discussion - Introduce Yourself",
        category: "Activity Assignments",
        dueDate: "2026-01-19",
        status: "completed",
        scoreEarned: 100,
        scorePossible: 100,
      },
      {
        id: "ecn-worksheet-ch10",
        courseId: "ecn-222-002-003",
        name: "Class Worksheet (Ch10)_Upload here",
        category: "Class Participation",
        dueDate: "2026-01-29",
        status: "completed",
        scoreEarned: 100,
        scorePossible: 100,
      },
      {
        id: "ecn-homework-ch10",
        courseId: "ecn-222-002-003",
        name: "Homework (Ch10)",
        category: "Homework Assignments",
        dueDate: "2026-02-01",
        status: "completed",
        scoreEarned: 100,
        scorePossible: 100,
      },
      {
        id: "ecn-activity-2",
        courseId: "ecn-222-002-003",
        name: "Activity 2: Mapping GDP_UPLOAD HERE",
        category: "Activity Assignments",
        dueDate: "2026-02-01",
        status: "completed",
        scoreEarned: 22,
        scorePossible: 25,
      },
      {
        id: "ecn-homework-ch11",
        courseId: "ecn-222-002-003",
        name: "Homework (Ch11)",
        category: "Homework Assignments",
        dueDate: "2026-02-10",
        status: "completed",
        scoreEarned: 97.92,
        scorePossible: 100,
      },
      {
        id: "ecn-worksheet-ch11",
        courseId: "ecn-222-002-003",
        name: "Class Worksheet (Ch11)_Upload here",
        category: "Class Participation",
        dueDate: "2026-02-10",
        status: "completed",
        scoreEarned: 0.9,
        scorePossible: 1,
      },
      {
        id: "ecn-homework-ch15",
        courseId: "ecn-222-002-003",
        name: "Homework (Ch15)",
        category: "Homework Assignments",
        dueDate: "2026-02-15",
        status: "completed",
        scoreEarned: 100,
        scorePossible: 100,
      },
      {
        id: "ecn-worksheet-ch15",
        courseId: "ecn-222-002-003",
        name: "Class Worksheet (Ch15)_Formula Sheet",
        category: "Class Participation",
        dueDate: "2026-02-16",
        status: "completed",
        scoreEarned: 0.9,
        scorePossible: 1,
      },
      {
        id: "ecn-activity-3",
        courseId: "ecn-222-002-003",
        name: "Activity 3: Lifetime Inflation_UPLOAD HERE",
        category: "Activity Assignments",
        dueDate: "2026-02-23",
        status: "completed",
        scoreEarned: 24,
        scorePossible: 25,
      },
      {
        id: "ecn-worksheet-ch12",
        courseId: "ecn-222-002-003",
        name: "Class Worksheet (Ch12)_UPLOAD HERE",
        category: "Class Participation",
        dueDate: "2026-02-26",
        status: "completed",
        scoreEarned: 1,
        scorePossible: 1,
      },
      {
        id: "ecn-homework-ch12",
        courseId: "ecn-222-002-003",
        name: "Homework (Ch12)",
        category: "Homework Assignments",
        dueDate: "2026-03-08",
        status: "completed",
        scoreEarned: 100,
        scorePossible: 100,
      },
      {
        id: "ecn-worksheet-ch13",
        courseId: "ecn-222-002-003",
        name: "Class Worksheet (Ch13)_UPLOAD HERE",
        category: "Class Participation",
        dueDate: "2026-03-12",
        status: "completed",
        scoreEarned: 0.93,
        scorePossible: 1,
      },
      {
        id: "ecn-homework-ch13",
        courseId: "ecn-222-002-003",
        name: "Homework (Ch13)",
        category: "Homework Assignments",
        dueDate: "2026-03-15",
        status: "completed",
        scoreEarned: 100,
        scorePossible: 100,
      },
      {
        id: "ecn-homework-ch16",
        courseId: "ecn-222-002-003",
        name: "Homework (Ch16)",
        category: "Homework Assignments",
        dueDate: "2026-03-22",
        status: "completed",
        scoreEarned: 100,
        scorePossible: 100,
      },
      {
        id: "ecn-exam-1",
        courseId: "ecn-222-002-003",
        name: "Exam 1",
        category: "Exam 1",
        dueDate: "2026-02-20",
        status: "completed",
        scoreEarned: 39,
        scorePossible: 40,
      },
      {
        id: "ecn-exam-2",
        courseId: "ecn-222-002-003",
        name: "Exam 2 - Save the Date",
        category: "Exam 2",
        dueDate: "2026-03-23",
        status: "not-started",
        scoreEarned: null,
        scorePossible: 100,
      },
      {
        id: "ecn-final",
        courseId: "ecn-222-002-003",
        name: "Final Exam",
        category: "Final Exam",
        dueDate: "2026-05-08",
        status: "not-started",
        scoreEarned: null,
        scorePossible: 100,
      },
    ],
  },

  {
    id: "eng-110-001-002-013",
    name: "Introduction to Literature",
    credits: 3,
    targetGrade: 97,
    finalExamWeight: 25,
    categories: [
      { name: "Literary Analysis Essay", weight: 20 },
      { name: "Midterm", weight: 10 },
      { name: "Final Project", weight: 25 },
      { name: "Class Activities", weight: 20 },
      { name: "Journals & Reflections", weight: 15 },
      { name: "Participation and Professionalism", weight: 10 },
    ],
    assignments: [
      {
        id: "eng110-journal-1",
        courseId: "eng-110-001-002-013",
        name: 'Journal #1 - Introducing Yourself',
        category: "Journals & Reflections",
        dueDate: "2026-01-16",
        status: "completed",
        scoreEarned: 10,
        scorePossible: 10,
      },
      {
        id: "eng110-db-1",
        courseId: "eng-110-001-002-013",
        name: 'Discussion Board #1: "The Story of an Hour" and "Janus" QQR',
        category: "Class Activities",
        dueDate: "2026-01-21",
        status: "completed",
        scoreEarned: 10,
        scorePossible: 10,
      },
      {
        id: "eng110-syllabus-quiz",
        courseId: "eng-110-001-002-013",
        name: "110 Syllabus Quiz",
        category: "Class Activities",
        dueDate: "2026-01-23",
        status: "completed",
        scoreEarned: 17,
        scorePossible: 17,
      },
      {
        id: "eng110-video-quiz",
        courseId: "eng-110-001-002-013",
        name: "Writing about Literature Video Quiz: Active Reading",
        category: "Class Activities",
        dueDate: "2026-01-23",
        status: "completed",
        scoreEarned: 10,
        scorePossible: 10,
      },
      {
        id: "eng110-db-2",
        courseId: "eng-110-001-002-013",
        name: 'Discussion Board #2: "Eight Bites" QQR',
        category: "Class Activities",
        dueDate: "2026-01-28",
        status: "completed",
        scoreEarned: 10,
        scorePossible: 10,
      },
      {
        id: "eng110-quotations-quiz",
        courseId: "eng-110-001-002-013",
        name: "Writing about Literature: Using Quotations Effectively Quiz",
        category: "Class Activities",
        dueDate: "2026-01-30",
        status: "completed",
        scoreEarned: 10,
        scorePossible: 10,
      },
      {
        id: "eng110-class-questions-2-2",
        courseId: "eng-110-001-002-013",
        name: "Class Questions 2/2",
        category: "Participation and Professionalism",
        dueDate: "2026-02-04",
        status: "completed",
        scoreEarned: 5,
        scorePossible: 5,
      },
      {
        id: "eng110-journal-2",
        courseId: "eng-110-001-002-013",
        name: "Journal 2 - Methods of Argument: Contemporary Conversations",
        category: "Journals & Reflections",
        dueDate: "2026-02-06",
        status: "completed",
        scoreEarned: 20,
        scorePossible: 20,
      },
      {
        id: "eng110-class-argument-analysis",
        courseId: "eng-110-001-002-013",
        name: "Class Argument Analysis 2/9",
        category: "Participation and Professionalism",
        dueDate: "2026-02-09",
        status: "completed",
        scoreEarned: 8,
        scorePossible: 10,
      },
      {
        id: "eng110-source-work-quiz",
        courseId: "eng-110-001-002-013",
        name: 'Reed - "Killing Like They Do in the Movies" - Source Work',
        category: "Class Activities",
        dueDate: "2026-02-11",
        status: "completed",
        scoreEarned: 9,
        scorePossible: 10,
      },
      {
        id: "eng110-mla-review",
        courseId: "eng-110-001-002-013",
        name: "MLA Review Certificate",
        category: "Class Activities",
        dueDate: "2026-02-13",
        status: "completed",
        scoreEarned: 10,
        scorePossible: 10,
      },
      {
        id: "eng110-campus-guest",
        courseId: "eng-110-001-002-013",
        name: 'Campus "The Guest"',
        category: "Class Activities",
        dueDate: "2026-02-18",
        status: "completed",
        scoreEarned: 10,
        scorePossible: 10,
      },
      {
        id: "eng110-precis-attempt",
        courseId: "eng-110-001-002-013",
        name: "Precis Attempt",
        category: "Class Activities",
        dueDate: "2026-02-18",
        status: "completed",
        scoreEarned: 15,
        scorePossible: 15,
      },
      {
        id: "eng110-paper-1-archive-final",
        courseId: "eng-110-001-002-013",
        name: "Paper 1: Argument Archive Final",
        category: "Literary Analysis Essay",
        dueDate: "2026-03-13",
        status: "completed",
        scoreEarned: 17,
        scorePossible: 20,
      },
      {
        id: "eng110-major-lens-social-issue",
        courseId: "eng-110-001-002-013",
        name: "Major (Lens) and Social Issue_due after class 3/16",
        category: "Participation and Professionalism",
        dueDate: "2026-03-16",
        status: "completed",
        scoreEarned: 5,
        scorePossible: 5,
      },
      {
        id: "eng110-social-conversations-issues",
        courseId: "eng-110-001-002-013",
        name: "Social Conversations and Issues",
        category: "Participation and Professionalism",
        dueDate: "2026-03-16",
        status: "completed",
        scoreEarned: 5,
        scorePossible: 5,
      },
      {
        id: "eng110-first-sources",
        courseId: "eng-110-001-002-013",
        name: "First Sources",
        category: "Participation and Professionalism",
        dueDate: "2026-03-18",
        status: "completed",
        scoreEarned: 9,
        scorePossible: 10,
      },
      {
        id: "eng110-developing-inquiry-focus-annotations",
        courseId: "eng-110-001-002-013",
        name: "Developing Inquiry and Focus-Annotations",
        category: "Literary Analysis Essay",
        dueDate: "2026-03-20",
        status: "in-progress",
        scoreEarned: null,
        scorePossible: 10,
      },
      {
        id: "eng110-cars-group-annotation",
        courseId: "eng-110-001-002-013",
        name: "CARS-Group Annotation",
        category: "Class Activities",
        dueDate: "2026-03-23",
        status: "in-progress",
        scoreEarned: null,
        scorePossible: 10,
      },
      {
        id: "eng110-developing-inquiry-2",
        courseId: "eng-110-001-002-013",
        name: "Developing Inquiry II",
        category: "Literary Analysis Essay",
        dueDate: "2026-03-29",
        status: "not-started",
        scoreEarned: null,
        scorePossible: 10,
      },
      {
        id: "eng110-final-project",
        courseId: "eng-110-001-002-013",
        name: "Final Project",
        category: "Final Project",
        dueDate: "2026-05-01",
        status: "not-started",
        scoreEarned: null,
        scorePossible: 100,
      },
      {
        id: "eng110-midterm",
        courseId: "eng-110-001-002-013",
        name: "Midterm",
        category: "Midterm",
        dueDate: "2026-04-01",
        status: "not-started",
        scoreEarned: null,
        scorePossible: 100,
      },
    ],
  },

  {
    id: "eng-201-023",
    name: "College Writing and Research",
    credits: 3,
    targetGrade: 92,
    finalExamWeight: 20,
    categories: [
      { name: "Essays", weight: 40 },
      { name: "Assignments", weight: 10 },
      { name: "Presentations", weight: 20 },
      { name: "Quizzes", weight: 10 },
      { name: "Journals", weight: 20 },
    ],
    assignments: [
      {
        id: "eng201-chronicle",
        courseId: "eng-201-023",
        name: "How Is AI Changing Higher Education -- The Chronicle of Higher Education",
        category: "Assignments",
        dueDate: "2026-01-13",
        status: "completed",
        scoreEarned: 30,
        scorePossible: 30,
      },
      {
        id: "eng201-hsu-commentary-1",
        courseId: "eng-201-023",
        name: "Hsu-Commentary and Source Analysis",
        category: "Assignments",
        dueDate: "2026-01-21",
        status: "completed",
        scoreEarned: 5,
        scorePossible: 5,
      },
      {
        id: "eng201-ai-journal-1",
        courseId: "eng-201-023",
        name: "AI Journal 1",
        category: "Journals",
        dueDate: "2026-01-23",
        status: "completed",
        scoreEarned: 20,
        scorePossible: 20,
      },
      {
        id: "eng201-hsu-commentary-2",
        courseId: "eng-201-023",
        name: "Hsu Commentary and Source Analysis",
        category: "Assignments",
        dueDate: "2026-01-23",
        status: "completed",
        scoreEarned: 15,
        scorePossible: 15,
      },
      {
        id: "eng201-syllabus-quiz",
        courseId: "eng-201-023",
        name: "Syllabus Quiz",
        category: "Quizzes",
        dueDate: "2026-01-26",
        status: "completed",
        scoreEarned: 28,
        scorePossible: 28,
      },
      {
        id: "eng201-ben-schwartz-choice",
        courseId: "eng-201-023",
        name: 'Ben Schwartz - "Shutting Up" or Your Choice',
        category: "Assignments",
        dueDate: "2026-01-30",
        status: "completed",
        scoreEarned: 17,
        scorePossible: 20,
      },
      {
        id: "eng201-first-day-questions",
        courseId: "eng-201-023",
        name: "First Day Questions",
        category: "Assignments",
        dueDate: "2026-01-15",
        status: "completed",
        scoreEarned: 5,
        scorePossible: 5,
      },
      {
        id: "eng201-hsu-quiz-answers",
        courseId: "eng-201-023",
        name: "Hsu Quiz Answers",
        category: "Quizzes",
        dueDate: "2026-02-01",
        status: "completed",
        scoreEarned: 12,
        scorePossible: 12,
      },
      {
        id: "eng201-respond-occasions-argument",
        courseId: "eng-201-023",
        name: "Respond: Occasions for Argument",
        category: "Assignments",
        dueDate: "2026-01-28",
        status: "completed",
        scoreEarned: 15,
        scorePossible: 15,
      },
      {
        id: "eng201-journal-2",
        courseId: "eng-201-023",
        name: "Journal 2 - Methods of Argument: Contemporary Conversations",
        category: "Journals",
        dueDate: "2026-02-06",
        status: "completed",
        scoreEarned: 20,
        scorePossible: 20,
      },
      {
        id: "eng201-paper-1-rough",
        courseId: "eng-201-023",
        name: "Paper 1 Rough Draft",
        category: "Journals",
        dueDate: "2026-02-27",
        status: "completed",
        scoreEarned: 15,
        scorePossible: 20,
      },
      {
        id: "eng201-paper-1-final",
        courseId: "eng-201-023",
        name: "Paper 1: Argument Archive Final",
        category: "Essays",
        dueDate: "2026-03-13",
        status: "completed",
        scoreEarned: 17,
        scorePossible: 20,
      },
      {
        id: "eng201-major-lens",
        courseId: "eng-201-023",
        name: "Major (Lens) and Social Issue_due after class 3/16",
        category: "Assignments",
        dueDate: "2026-03-16",
        status: "completed",
        scoreEarned: 5,
        scorePossible: 5,
      },
      {
        id: "eng201-social-conversations",
        courseId: "eng-201-023",
        name: "Social Conversations and Issues",
        category: "Assignments",
        dueDate: "2026-03-16",
        status: "completed",
        scoreEarned: 5,
        scorePossible: 5,
      },
      {
        id: "eng201-first-sources",
        courseId: "eng-201-023",
        name: "First Sources",
        category: "Assignments",
        dueDate: "2026-03-18",
        status: "completed",
        scoreEarned: 9,
        scorePossible: 10,
      },
      {
        id: "eng201-developing-inquiry",
        courseId: "eng-201-023",
        name: "Developing Inquiry and Focus-Annotations",
        category: "Essays",
        dueDate: "2026-03-20",
        status: "in-progress",
        scoreEarned: null,
        scorePossible: 10,
      },
      {
        id: "eng201-cars-group-annotation",
        courseId: "eng-201-023",
        name: "CARS-Group Annotation",
        category: "Assignments",
        dueDate: "2026-03-23",
        status: "in-progress",
        scoreEarned: null,
        scorePossible: 10,
      },
      {
        id: "eng201-developing-inquiry-2",
        courseId: "eng-201-023",
        name: "Developing Inquiry II",
        category: "Assignments",
        dueDate: "2026-03-29",
        status: "not-started",
        scoreEarned: null,
        scorePossible: 10,
      },
      {
        id: "eng201-annotated-bib-presentation",
        courseId: "eng-201-023",
        name: "Annotated Bibliography Presentation",
        category: "Presentations",
        dueDate: "2026-04-10",
        status: "not-started",
        scoreEarned: null,
        scorePossible: 20,
      },
    ],
  },

  {
    id: "evsl-195-211",
    name: "Environmental Science Lab",
    credits: 1,
    targetGrade: 99,
    finalExamWeight: 5,
    categories: [
      { name: "Lab Exercises", weight: 80 },
      { name: "Intro Assignments", weight: 5 },
      { name: "Critical Reflection", weight: 5 },
      { name: "Skills Check", weight: 5 },
      { name: "Final Lab Exam", weight: 5 },
    ],
    assignments: [
      {
        id: "evsl-prelab-part4",
        courseId: "evsl-195-211",
        name: "Pre-Lab Submission Portal: Climate Change Background PART 4",
        category: "Lab Exercises",
        dueDate: "2026-01-23",
        status: "completed",
        scoreEarned: 10,
        scorePossible: 10,
      },
      {
        id: "evsl-lab-agreement",
        courseId: "evsl-195-211",
        name: "Grade Portal: Lab Agreement and Honor Code Signatures",
        category: "Intro Assignments",
        dueDate: "2026-01-23",
        status: "completed",
        scoreEarned: 10,
        scorePossible: 10,
      },
      {
        id: "evsl-syllabus-quiz",
        courseId: "evsl-195-211",
        name: "Quiz: Syllabus, Lab Manual and Course Policies",
        category: "Intro Assignments",
        dueDate: "2026-01-23",
        status: "completed",
        scoreEarned: 8.5,
        scorePossible: 10,
      },
      {
        id: "evsl-statistics-evs",
        courseId: "evsl-195-211",
        name: "Statistics in EVS",
        category: "Intro Assignments",
        dueDate: "2026-01-23",
        status: "completed",
        scoreEarned: 10,
        scorePossible: 10,
      },
      {
        id: "evsl-lab-submission-climate",
        courseId: "evsl-195-211",
        name: "Lab Submission Portal: Climate Change",
        category: "Lab Exercises",
        dueDate: "2026-01-30",
        status: "completed",
        scoreEarned: 30,
        scorePossible: 30,
      },
      {
        id: "evsl-skills-check",
        courseId: "evsl-195-211",
        name: "Skills Check",
        category: "Skills Check",
        dueDate: "2026-02-20",
        status: "completed",
        scoreEarned: 4,
        scorePossible: 4,
      },
      {
        id: "evsl-critical-reflection",
        courseId: "evsl-195-211",
        name: "Critical Reflection",
        category: "Critical Reflection",
        dueDate: "2026-04-20",
        status: "not-started",
        scoreEarned: null,
        scorePossible: 10,
      },
      {
        id: "evsl-final-lab-exam",
        courseId: "evsl-195-211",
        name: "Final Lab Exam",
        category: "Final Lab Exam",
        dueDate: "2026-05-01",
        status: "not-started",
        scoreEarned: null,
        scorePossible: 100,
      },
    ],
  },
];
